### ISSUE TITLE
invalid resource directory name，NavigationDrawerSI-master\app\src\main\res web_hi_res_512.png

### ISSUE THREAD

**Issue by yaochangliang159** [mmBs/NavigationDrawerSI#2]
\NavigationDrawerSI-master\app\src\main\res\layout\fragment_two.xml:17: 
error: No resource identifier found for attribute 'typeface' in package 'mmbialas.pl.navigationdrawersi'
is this project have an library?

**Comment by mmBs** [comment]
Hey, thanks for notifying me about that. All libraries are added as dependencies. I updated all files you need to build the project. 
Please, pull new changes and build the app in terminal using: 

```
./gradlew build 
```

and then 

```
./gradlew installDebug 
```

to install the app on your phone.
